-- =====================================================================
-- seed.sql — Proyecto Astronomía Programación III
-- =====================================================================
-- Los datos se cargan automáticamente desde la API externa.
-- Ejecutar: POST /api/admin/importar desde la aplicación.
--
-- Para limpiar y reimportar desde cero: ejecutar reset.sql
-- =====================================================================
